"""Add project_users join table

Revision ID: d5d898194de4
Revises: bf2d340582e9
Create Date: 2026-09-25 07:31:08.586820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d898194de4'
down_revision: Union[str, Sequence[str], None] = 'bf2d340582e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_users',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.drop_index(op.f('idx_problems_search_vector'), table_name='problems', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_problems_search_vector'), 'problems', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_table('project_users')
    # ### end Alembic commands ###
